<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Platforms>x64</Platforms>
    <AssemblyName>SCPSLBot.Components</AssemblyName>
    <RootNamespace>SCPSLBot.Components</RootNamespace>

    <LangVersion>12.0</LangVersion>
    <Nullable>warnings</Nullable>

    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <ImplicitlyExpandDesignTimeFacades>false</ImplicitlyExpandDesignTimeFacades>

    <AssemblySearchPaths>$(SL_REFERENCES);$(AssemblySearchPaths)</AssemblySearchPaths>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>embedded</DebugType>
    <DefineConstants>$(DefineConstants);ENABLE_PROFILER</DefineConstants>
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>portable</DebugType>
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>

  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SL_APPDATA)\LabAPI\plugins\global">
      <Output TaskParameter="CopiedFiles" ItemName="FilesCopied"/>
    </Copy>
    <Message Text="Files copied @(FilesCopied)" Importance="high"/>
  </Target>

  
  <ItemGroup>
    <InternalsVisibleTo Include="SCPSLBot"/>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <Private>false</Private>
    </Reference>
    <Reference Include="mscorlib" />
    <Reference Include="netstandard" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectCapability Remove="LaunchProfiles" />
    <ProjectCapability Remove="SharedProjectReferences" />
    <ProjectCapability Remove="ReferenceManagerSharedProjects" />
    <ProjectCapability Remove="ReferenceManagerProjects" />
    <ProjectCapability Remove="COMReferences" />
    <ProjectCapability Remove="ReferenceManagerCOM" />
    <ProjectCapability Remove="AssemblyReferences" />
    <ProjectCapability Remove="ReferenceManagerAssemblies" />
  </ItemGroup>

</Project>
